# Generated by Django 5.2.15 on 2026-07-08 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_migrate_is_completed_to_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="is_completed",
        ),
    ]
